# config.yaml (설정 파일)
# 아래 정보는 한국투자증권 API 홈페이지 및 텔레그램에서 발급받아 채워주세요.

# 한국투자증권 API 정보 (모의투자 또는 실전투자)
KIS:
  APP_KEY: "PSeV41RVGiC1CGtlBbYo4d83XcakSRB2XcHV"
  APP_SECRET: "btcu4IguQNbe1W9+GyrDS73r09DwNbxL7RyY8MGKEhMGnn431Mke7nYYSQXtwUc7qpQf/u7tBjXLi7YABJohrA6Uy/d+d8Ocb1ehC1R8xs7OLvlYM2NWd/D7GS52dAB3tJv6xHglNnIVczJckYtyde7Eg2nsadv7qBCf4q13AGGnDLQDdcM="
  ACCOUNT_NO: "4455092301"  # 계좌번호 8자리 + 상품코드 2자리 (종합계좌=01)
  IS_MOCK: false  # true면 모의투자, false면 실전투자

# 텔레그램 봇 정보
TELEGRAM:
  BOT_TOKEN: "8647509036:AAEVZonRQAWtd7an0c5C2dfftJ1vX_0lbKQ"
  CHAT_ID: "8769164926"

# 구글 제미나이(Gemini) API 정보
GEMINI:
  API_KEY: ""
